### PR TITLE
Add JavaScript  function to my portfolio mobile nav menu and button

### PR DESCRIPTION
**Pull request by sidiksam**
### My-portfolio

- Add javaScript to the project
- change the hover style in my nav bar
- Add CSS style
- set "a" tags to point in a certain direction

### CODE REVIEW

**Review by Bondok6 — CHANGES_REQUESTED** [review]
## Hi @sidiksam 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Great using Gitflow ✅
- Well file structure ✅
- Profesional README.md file ✅

## Required Changes ♻️
- [ ] I noticed you didn't add the javaScript Linter, and according to the requirements you should add the [JavaScript + HTML + CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js), so Kindly add it 👌

image


- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi @sidiksam , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] As the previous code reviewer said please you should add the [JavaScript + HTML + CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

 _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sidiksam** [comment]
> Hi @sidiksam ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * [x]  As the previous code reviewer said please you should add the [JavaScript + HTML + CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js).
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi, I have added it I don't know why you said it is not there. After adding the javaScript linter it takes me 2 hours to fix the errors that pop up in the javascript code

**Comment by ShahierNashaat** [comment]
What I mean is that the checks for the eslint don't run in your pull request also you should use [this file](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) in your `linters` file in the  .github/workflow folder.

**Comment by sidiksam** [comment]
> What I mean is that the checks for the eslint don't run in your pull request also you should use [this file](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) in your `linters` file in the .github/workflow folder.

Okay, I add it into the linter file.

**Pull request merged**
